### ISSUE TITLE
Mod won't load in game

### ISSUE THREAD

**Issue by VaudevillianVeteran** [Kein/ABPML#2]
AtomicHeart with installed https://www.nexusmods.com/atomicheart/mods/1 to "[Library]\Atomic Heart\AtomicHeart\Content\Paks".

UE 4.27.2, making a new empty project, all settings on default. Following the Creating compatible mods instructions (making an Actor based one), cooking, packing with UnrealPak (lite version for modders by FluffyQuack), trying in game - nope, not found: shift+f2 output console says 0 mods found/loaded. Checked the structure and naming by unpacking your QoL mod - seems quite the same.

**Comment by Kein** [comment]
Upload your PAK here and also how me your Content Browser inside Editor:
![image](https://user-images.githubusercontent.com/623756/220805354-c1e93ebe-4677-4691-a0df-46484d93e4d8.png)

**Comment by VaudevillianVeteran** [comment]
My Engine Content->ABPML only has Public folder, Core is missing. Downloaded from here (Code->Download zip), BinaryData copied following the instructions (it only has Public folder inside), validate was success, then did resave all.

**Comment by Kein** [comment]
`Core` should be missing, it is only in full sources.
I've just tested with public template and it works. I think you've made mistake somewhere.
Right-click on `ABPML` in Engine Content and do Validate, then do Resave All.
Did you inherit DataAsset from `PDA_ABPML_ModConfig`?
Did you configure it? Did you not forget to assign soft reference inside data asset?

I also suspect your PAK might not pak'ed properly (wrong mount point or ProjectName).  Can you post it? I suggest to use vanilla UEPak for sanity check or use packaging and chunking system. Alternatively, you also can try this to verify (dont use it for paking):
https://github.com/trumank/repak
Make sure your MountPoint specified correctly:
```
repak.exe list ABPML_mod2.pak
ABPML_ModConf_TestMod2.uasset
ABPML_ModConf_TestMod2.uexp
ABPML_Mod_TestMod2.uasset
ABPML_Mod_TestMod2.uexp

repak.exe info ABPML_mod2.pak
mount point: ../../../AtomicHeart/Content/Mods/TestMod2/
version: V11
version major: Fnv64BugFix
4 file entries
```

**Comment by VaudevillianVeteran** [comment]
Validate: checked 10, passed 10. Then saving all.

Yes, inherited, made an actor, configured. The pak is ok as hex editing vanilla assets and repacking works + the other loader works fine, so the game is able to read it for sure. Name and mount point are correct. Will check packing with the native packer.

ABPML_ModConf_TestMod.uasset
ABPML_ModConf_TestMod.uexp
ABPML_Mod_TestMod.uasset
ABPML_Mod_TestMod.uexp

mount point: ../../../AtomicHeart/Content/Mods/TestMod/
version: V3
version major: CompressionEncryption
4 file entries

**Comment by Kein** [comment]
`version: V3`
wont work for UE4.27, you need v11

**Comment by Kein** [comment]
Not sure about v3 for UE4.27
How are you naming your PAK? It is either not reading/mounting it properly or something else is a miss, I might need to look at the PAK itself, can you make a dummy TestMod?

I've just tested on empty project again, it works. Your UE4.27 Editor is vanilla, correct? 

Also, use [UASSETGUI](https://github.com/atenfyr/UAssetGUI) to open your ModConf cooked uasset-file, navigate to `Export Information` and ensure field `bIsAsset` is `True` there:

![image](https://user-images.githubusercontent.com/623756/220811993-4c387d99-14a9-4e98-940a-de0aa3d4b90f.png)

**Comment by VaudevillianVeteran** [comment]
You're wrong - it works with 4.27, I can see packages being loaded in game. Editor is vanilla, installed with Epic launcher.

Tested by generating a chunk with the editor - same, won't load.

**Comment by Kein** [comment]
Drop the test PAK here, I will check on my game.

**Comment by VaudevillianVeteran** [comment]
OK, problem found. Turns out it's UE4 editor issue (don't remember having in with 5): when you just select the parent from all classes it won't work. You might want to add that into the description: if your asset is a proper data asset it will have a red background in content browser, if you're seeing a blue background it's not a correct one, won't be considered a data asset and won't work.

And FYI: good old lightweight unrealpak does work. Much faster than setting up chinks in editor and packaging the project.

Thanks for a nice tool, товарищ! ;)
