### ISSUE TITLE
Returnal implementation  

### ISSUE THREAD

**Issue by BurgersMcFly** [Kein/ABPML#3]
[Config.zip](https://github.com/Kein/ABPML/files/10813442/Config.zip)

**Comment by Kein** [comment]
Okay, somewhere here `%LOCALAPPDATA%\Returnal` you can find generated by the game `Engine.ini`. I assume Returnal is on 4.27, download ABPML from Atomic Heart and drop it into game's `Paks/` folder. Open aforementioned `Engine.ini` and add this to the end:

```
[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Engine/ABPML/ABPML_BootstrapMap.ABPML_BootstrapMap

[/Engine/ABPML/Public/O_ABPML_Settings.O_ABPML_Settings_C]
TravelDelay=0
bEnableAutoTravel=False
GameStartupMap=/Game/Maps/System/Boot.Boot

; This might not be necessary or even bad, depending how game's boot screen
; is set up, but let's test it from the get-go
[/Script/MoviePlayer.MoviePlayerSettings]
-StartupMovies=Logos
!StartupMovies=ClearArray
bWaitForMoviesToComplete=False
bMoviesAreSkippable=True
bIsFirstBoot=False
```
Mark the file read-only for now (to unsure it is not overwritten).
Launch the game. Ideally you should be met with black screen, try pressing SHIFT+F2 or tilde key on it.

**Comment by BurgersMcFly** [comment]
Returnal's version is 4.25.1.0 so I had to convert your file to make it work. Game launches with startup movies and then black screen. When pressing shift f2 I'm met with this:

![Returnal-Win64-Shipping_nRTSZhfv08](https://user-images.githubusercontent.com/26502050/220912620-0f9c3279-f487-4d55-bd48-b09fdbf81da2.png)

Pressing tilde opens the console.

Can't do anything else.

**Comment by Kein** [comment]
That looks promising, I'm surprised it loaded 4.27.2 assets in 4.25. That being said, it wont do and wont be stable, I will have to repackage it for 4.25. Give me a few minutes.

**Comment by BurgersMcFly** [comment]
Yea I didn't expect it to work either lol! I first converted your 4.23 version to try it out and it was crashing with "Map not found" or something like that.

**Comment by Kein** [comment]
Try this one: 
[ABPML_UE4_25_P.zip](https://github.com/Kein/ABPML/files/10813851/ABPML_UE4_25_P.zip)

Also I made a typo in config, fixed the snippet above.

**Comment by BurgersMcFly** [comment]
Game boots normally but instead of spawning into the main world it does this:

![Returnal-Win64-Shipping_9GxYOCKPLP](https://user-images.githubusercontent.com/26502050/220929003-ff7924cc-7276-40d9-812b-ef8090a782c9.png)

Shift f2 and tilde works but mouse is invisible when in shift f2 D:

**Comment by BurgersMcFly** [comment]
Correction for the above:

Had to fix engine.ini my bad!

Now getting this message:

![Returnal-Win64-Shipping_138hErdg9e](https://user-images.githubusercontent.com/26502050/220930303-a3ce6031-21bc-4188-b291-02876d496eec.png)

**Comment by Kein** [comment]
Cool, enable autostartup:
`bEnableAutoTravel=True`

**Comment by BurgersMcFly** [comment]
Yep works fine now! Now all I have to do is find a way to enable the debug menus and the cheats lol.

**Comment by Kein** [comment]
If you decide to publish mods for it, let me know, I will package an unattend-setup for it (or you ca do it yourself)

**Comment by BurgersMcFly** [comment]
Got you mate. Thanks for the help!

**Comment by BurgersMcFly** [comment]
Is there anyway to dump console commands if dumpconsolecommands is failing? Am I supposed to do something to make the console functional?

![Returnal-Win64-Shipping_n48WHHpqRG](https://user-images.githubusercontent.com/26502050/221331691-21f8ea78-30ab-4c12-a75e-4d28c3d4a7db.png)

**Comment by Kein** [comment]
That functionality stripped from the release builds, restoring it requires patching binary.
If you want to know game's own built-in convars and  commands you need to analyze the binary for unicode text.
As for `fly`, `walk`  and `enable cheats` it is part of CheatManager's functionality. ABPML should restore it on each new World change. Show me the log.
